version: "3"

volumes:
  mvn-cache:
  backend-database-data:

networks:
  database_network:
  proxy_network:

services:
  backend-database:
    image: postgres:11.1-alpine
    volumes:
      - backend-database-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network
    environment:
      - POSTGRES_DB=${BACKEND_DATABASE_NAME}
      - POSTGRES_USER=${BACKEND_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${BACKEND_DATABASE_PASSWORD}

  backend:
    image: leandrohsilveira/kikaha-server:1.1
    volumes:
      - ./backend/ibpms:/home/kikaha/ibpms
      - mvn-cache:/root/.m2
    networks:
      - database_network
      - proxy_network
    environment:
      - MODULE_NAME=ibpms
      - BACKEND_DATABASE_DOMAIN=${BACKEND_DATABASE_DOMAIN}
      - BACKEND_DATABASE_PORT=${BACKEND_DATABASE_PORT}
      - BACKEND_DATABASE_NAME=${BACKEND_DATABASE_NAME}
      - BACKEND_DATABASE_USERNAME=${BACKEND_DATABASE_USERNAME}
      - BACKEND_DATABASE_PASSWORD=${BACKEND_DATABASE_PASSWORD}
    depends_on:
      - backend-database
    command: bash --login -c "envsubst < ./ibpms/env.template.yml > ./ibpms/env.yml && kikaha run_app $${MODULE_NAME}"

  frontend:
    image: nginx:1.15.7-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks: 
      - proxy_network
  
  proxy:
    image: nginx:1.15.7-alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks: 
      - proxy_network