version: "3"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./frontend/src:/home/app/src
      - ./frontend/public:/home/app/public
      - ./frontend/webpack.config.js:/home/app/webpack.config.js
      - ./frontend/.babelrc:/home/app/.babelrc

